# Generated by Django 5.0.6 on 2026-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del parque')),
                ('direccional', models.CharField(max_length=300, verbose_name='Dirección')),
                ('servicios', models.TextField(verbose_name='Servicios disponibles')),
                ('horario', models.CharField(max_length=150, verbose_name='Horario de atención')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tiene_cabanas', models.BooleanField(default=False, verbose_name='¿Tiene cabañas?')),
                ('cap_camping', models.PositiveIntegerField(default=0, verbose_name='Capacidad máxima camping')),
                ('cap_cabanas', models.PositiveIntegerField(default=0, verbose_name='Capacidad máxima cabañas')),
                ('ocupados_camping', models.PositiveIntegerField(default=0, verbose_name='Lugares camping ocupados')),
                ('ocupados_cabanas', models.PositiveIntegerField(default=0, verbose_name='Lugares cabañas ocupados')),
                ('activo', models.BooleanField(default=True, verbose_name='Parque activo')),
            ],
            options={
                'verbose_name': 'Parque',
                'verbose_name_plural': 'Parques',
                'ordering': ['nombre'],
            },
        ),
    ]
