# Generated by Django 5.0.6 on 2026-05-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parques', '0001_initial'),
        ('reservaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='parques.parque', verbose_name='Parque'),
        ),
    ]
